# Generated by Django 3.0.3 on 2024-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240605_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='concentration_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='concentration_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
