# Generated by Django 3.0.3 on 2024-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240605_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
